var SubjectConstants = {
  ADD_SUBJECT: "ADD_SUBJECT",
  SUBJECTS_RECEIVED: "SUBJECTS_RECEIVED",
  REMOVE_SUBJECT: "REMOVE_SUBJECT",
  ADD_DECK: "ADD_DECK",
  REMOVE_DECK: "REMOVE_DECK"
};

module.exports = SubjectConstants;
